project_id = "nbcqwpysqgyxrrbgtmkw"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.checkalt-webhook]
    verify_jwt = false
