 CREATE OR REPLACE FUNCTION public.loss_draft_action(p_loss_draft_id uuid, p_action text, p_actor_id uuid, p_amount numeric DEFAULT NULL::numeric, p_notes text DEFAULT NULL::text, p_extra jsonb DEFAULT '{}'::jsonb)                                                                                            +
  RETURNS void                                                                                                                                                                                                                                                                                                    +
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                +
  SECURITY DEFINER                                                                                                                                                                                                                                                                                                +
  SET search_path TO 'public'                                                                                                                                                                                                                                                                                     +
 AS $function$                                                                                                                                                                                                                                                                                                    +
 DECLARE                                                                                                                                                                                                                                                                                                          +
   v_draft public.loss_draft_tracking%ROWTYPE;                                                                                                                                                                                                                                                                    +
   v_old jsonb;                                                                                                                                                                                                                                                                                                   +
   v_new jsonb;                                                                                                                                                                                                                                                                                                   +
   v_tracking text;                                                                                                                                                                                                                                                                                               +
   v_check_id uuid;                                                                                                                                                                                                                                                                                               +
   v_target_status text;                                                                                                                                                                                                                                                                                          +
   v_move_to_endorsing boolean := false;                                                                                                                                                                                                                                                                          +
 BEGIN                                                                                                                                                                                                                                                                                                            +
   SELECT * INTO v_draft                                                                                                                                                                                                                                                                                          +
   FROM public.loss_draft_tracking                                                                                                                                                                                                                                                                                +
   WHERE id = p_loss_draft_id                                                                                                                                                                                                                                                                                     +
   FOR UPDATE;                                                                                                                                                                                                                                                                                                    +
                                                                                                                                                                                                                                                                                                                  +
   IF NOT FOUND THEN                                                                                                                                                                                                                                                                                              +
     RAISE EXCEPTION 'Loss draft record not found';                                                                                                                                                                                                                                                               +
   END IF;                                                                                                                                                                                                                                                                                                        +
                                                                                                                                                                                                                                                                                                                  +
   v_check_id := v_draft.check_intake_item_id;                                                                                                                                                                                                                                                                    +
                                                                                                                                                                                                                                                                                                                  +
   v_old := jsonb_build_object(                                                                                                                                                                                                                                                                                   +
     'escrow_status', v_draft.escrow_status,                                                                                                                                                                                                                                                                      +
     'monitoring_type', v_draft.monitoring_type,                                                                                                                                                                                                                                                                  +
     'total_escrowed', v_draft.total_escrowed,                                                                                                                                                                                                                                                                    +
     'draw_amount_released', v_draft.draw_amount_released,                                                                                                                                                                                                                                                        +
     'holdback_amount', v_draft.holdback_amount                                                                                                                                                                                                                                                                   +
   );                                                                                                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                                                                                  +
   v_tracking := NULLIF(p_extra->>'tracking_number', '');                                                                                                                                                                                                                                                         +
                                                                                                                                                                                                                                                                                                                  +
   IF p_action = 'set_monitoring_type' THEN                                                                                                                                                                                                                                                                       +
     UPDATE public.loss_draft_tracking                                                                                                                                                                                                                                                                            +
       SET monitoring_type = COALESCE(p_extra->>'monitoring_type', 'monitored'),                                                                                                                                                                                                                                  +
           updated_at = now()                                                                                                                                                                                                                                                                                     +
     WHERE id = p_loss_draft_id;                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                                  +
   ELSIF p_action = 'mark_sent' THEN                                                                                                                                                                                                                                                                              +
     UPDATE public.loss_draft_tracking                                                                                                                                                                                                                                                                            +
       SET escrow_status = 'sent_to_lender',                                                                                                                                                                                                                                                                      +
           check_sent_date = COALESCE(check_sent_date, CURRENT_DATE),                                                                                                                                                                                                                                             +
           tracking_number_sent = COALESCE(v_tracking, tracking_number_sent),                                                                                                                                                                                                                                     +
           last_contact_at = now(),                                                                                                                                                                                                                                                                               +
           updated_at = now()                                                                                                                                                                                                                                                                                     +
     WHERE id = p_loss_draft_id;                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                                  +
   ELSIF p_action = 'mark_received_back' THEN                                                                                                                                                                                                                                                                     +
     UPDATE public.loss_draft_tracking                                                                                                                                                                                                                                                                            +
       SET escrow_status = 'check_received_back',                                                                                                                                                                                                                                                                 +
           check_received_back_date = COALESCE(check_received_back_date, CURRENT_DATE),                                                                                                                                                                                                                           +
           updated_at = now()                                                                                                                                                                                                                                                                                     +
     WHERE id = p_loss_draft_id;                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                                  +
   ELSIF p_action = 'send_for_endorsements' THEN                                                                                                                                                                                                                                                                  +
     -- Move the check fully into the Endorsing stage and remove the loss                                                                                                                                                                                                                                         +
     -- draft tracking record. The check should no longer carry an escrow                                                                                                                                                                                                                                         +
     -- status while it is being endorsed.                                                                                                                                                                                                                                                                        +
     IF v_check_id IS NOT NULL THEN                                                                                                                                                                                                                                                                               +
       UPDATE public.check_intake_items                                                                                                                                                                                                                                                                           +
         SET status = 'endorsements_in_progress',                                                                                                                                                                                                                                                                 +
             check_stage = 'endorsing',                                                                                                                                                                                                                                                                           +
             updated_at = now()                                                                                                                                                                                                                                                                                   +
       WHERE id = v_check_id;                                                                                                                                                                                                                                                                                     +
                                                                                                                                                                                                                                                                                                                  +
       UPDATE public.claim_checks                                                                                                                                                                                                                                                                                 +
         SET check_stage = 'endorsing',                                                                                                                                                                                                                                                                           +
             updated_at = now()                                                                                                                                                                                                                                                                                   +
       WHERE check_intake_item_id = v_check_id;                                                                                                                                                                                                                                                                   +
                                                                                                                                                                                                                                                                                                                  +
       PERFORM public.seed_endorsements_from_payee_line(v_check_id);                                                                                                                                                                                                                                              +
     END IF;                                                                                                                                                                                                                                                                                                      +
                                                                                                                                                                                                                                                                                                                  +
     INSERT INTO public.check_audit_log (                                                                                                                                                                                                                                                                         +
       check_id, event_type, event_description, event_data, actor_id                                                                                                                                                                                                                                              +
     ) VALUES (                                                                                                                                                                                                                                                                                                   +
       v_check_id,                                                                                                                                                                                                                                                                                                +
       'loss_draft_moved_to_endorsing',                                                                                                                                                                                                                                                                           +
       'Loss draft tracking removed; check moved to Endorsing stage.',                                                                                                                                                                                                                                            +
       jsonb_build_object('loss_draft_id', p_loss_draft_id, 'prior_escrow_status', v_draft.escrow_status),                                                                                                                                                                                                        +
       p_actor_id                                                                                                                                                                                                                                                                                                 +
     );                                                                                                                                                                                                                                                                                                           +
                                                                                                                                                                                                                                                                                                                  +
     DELETE FROM public.loss_draft_tracking WHERE id = p_loss_draft_id;                                                                                                                                                                                                                                           +
     RETURN;                                                                                                                                                                                                                                                                                                      +
                                                                                                                                                                                                                                                                                                                  +
   ELSIF p_action = 'mark_escrowed' THEN                                                                                                                                                                                                                                                                          +
     UPDATE public.loss_draft_tracking                                                                                                                                                                                                                                                                            +
       SET escrow_status = 'escrowed',                                                                                                                                                                                                                                                                            +
           total_escrowed = COALESCE(p_amount, total_escrowed),                                                                                                                                                                                                                                                   +
           check_received_date = COALESCE(check_received_date, CURRENT_DATE),                                                                                                                                                                                                                                     +
           updated_at = now()                                                                                                                                                                                                                                                                                     +
     WHERE id = p_loss_draft_id;                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                                  +
   ELSIF p_action = 'request_draw' THEN                                                                                                                                                                                                                                                                           +
     UPDATE public.loss_draft_tracking                                                                                                                                                                                                                                                                            +
       SET escrow_status = 'first_draw_requested',                                                                                                                                                                                                                                                                +
           draw_amount_requested = COALESCE(draw_amount_requested, 0) + COALESCE(p_amount, 0),                                                                                                                                                                                                                    +
           draw_stage = draw_stage + 1,                                                                                                                                                                                                                                                                           +
           updated_at = now()                                                                                                                                                                                                                                                                                     +
     WHERE id = p_loss_draft_id;                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                                  +
   ELSIF p_action = 'record_release' THEN                                                                                                                                                                                                                                                                         +
     UPDATE public.loss_draft_tracking                                                                                                                                                                                                                                                                            +
       SET escrow_status = CASE                                                                                                                                                                                                                                                                                   +
             WHEN COALESCE(draw_amount_released, 0) + COALESCE(p_amount, 0) >= COALESCE(total_escrowed, 0)                                                                                                                                                                                                        +
               AND COALESCE(total_escrowed, 0) > 0                                                                                                                                                                                                                                                                +
             THEN 'final_release_complete'                                                                                                                                                                                                                                                                        +
             ELSE 'partial_release'                                                                                                                                                                                                                                                                               +
           END,                                                                                                                                                                                                                                                                                                   +
           draw_amount_released = COALESCE(draw_amount_released, 0) + COALESCE(p_amount, 0),                                                                                                                                                                                                                      +
           updated_at = now()                                                                                                                                                                                                                                                                                     +
     WHERE id = p_loss_draft_id;                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                                  +
   ELSIF p_action = 'record_holdback' THEN                                                                                                                                                                                                                                                                        +
     UPDATE public.loss_draft_tracking                                                                                                                                                                                                                                                                            +
       SET holdback_amount = COALESCE(holdback_amount, 0) + COALESCE(p_amount, 0),                                                                                                                                                                                                                                +
           updated_at = now()                                                                                                                                                                                                                                                                                     +
     WHERE id = p_loss_draft_id;                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                                  +
   ELSIF p_action = 'mark_final_release' THEN                                                                                                                                                                                                                                                                     +
     UPDATE public.loss_draft_tracking                                                                                                                                                                                                                                                                            +
       SET escrow_status = 'final_release_complete',                                                                                                                                                                                                                                                              +
           updated_at = now()                                                                                                                                                                                                                                                                                     +
     WHERE id = p_loss_draft_id;                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                                  +
   ELSIF p_action = 'admin_reset_status' THEN                                                                                                                                                                                                                                                                     +
     v_target_status := COALESCE(p_extra->>'target_status', v_draft.escrow_status);                                                                                                                                                                                                                               +
                                                                                                                                                                                                                                                                                                                  +
     IF v_target_status = 'endorsing' THEN                                                                                                                                                                                                                                                                        +
       -- Treat an admin reset to 'endorsing' the same as send_for_endorsements:                                                                                                                                                                                                                                  +
       -- move the check into Endorsing and drop the loss draft record entirely.                                                                                                                                                                                                                                  +
       IF v_check_id IS NOT NULL THEN                                                                                                                                                                                                                                                                             +
         UPDATE public.check_intake_items                                                                                                                                                                                                                                                                         +
           SET status = 'endorsements_in_progress',                                                                                                                                                                                                                                                               +
               check_stage = 'endorsing',                                                                                                                                                                                                                                                                         +
               updated_at = now()                                                                                                                                                                                                                                                                                 +
         WHERE id = v_check_id;                                                                                                                                                                                                                                                                                   +
                                                                                                                                                                                                                                                                                                                  +
         UPDATE public.claim_checks                                                                                                                                                                                                                                                                               +
           SET check_stage = 'endorsing',                                                                                                                                                                                                                                                                         +
               updated_at = now()                                                                                                                                                                                                                                                                                 +
         WHERE check_intake_item_id = v_check_id;                                                                                                                                                                                                                                                                 +
                                                                                                                                                                                                                                                                                                                  +
         PERFORM public.seed_endorsements_from_payee_line(v_check_id);                                                                                                                                                                                                                                            +
       END IF;                                                                                                                                                                                                                                                                                                    +
                                                                                                                                                                                                                                                                                                                  +
       INSERT INTO public.check_audit_log (                                                                                                                                                                                                                                                                       +
         check_id, event_type, event_description, event_data, actor_id                                                                                                                                                                                                                                            +
       ) VALUES (                                                                                                                                                                                                                                                                                                 +
         v_check_id,                                                                                                                                                                                                                                                                                              +
         'loss_draft_moved_to_endorsing',                                                                                                                                                                                                                                                                         +
         'Admin reset moved check to Endorsing; loss draft tracking removed.',                                                                                                                                                                                                                                    +
         jsonb_build_object('loss_draft_id', p_loss_draft_id, 'prior_escrow_status', v_draft.escrow_status),                                                                                                                                                                                                      +
         p_actor_id                                                                                                                                                                                                                                                                                               +
       );                                                                                                                                                                                                                                                                                                         +
                                                                                                                                                                                                                                                                                                                  +
       DELETE FROM public.loss_draft_tracking WHERE id = p_loss_draft_id;                                                                                                                                                                                                                                         +
       RETURN;                                                                                                                                                                                                                                                                                                    +
     ELSE                                                                                                                                                                                                                                                                                                         +
       UPDATE public.loss_draft_tracking                                                                                                                                                                                                                                                                          +
         SET escrow_status = v_target_status,                                                                                                                                                                                                                                                                     +
             updated_at = now()                                                                                                                                                                                                                                                                                   +
       WHERE id = p_loss_draft_id;                                                                                                                                                                                                                                                                                +
     END IF;                                                                                                                                                                                                                                                                                                      +
   END IF;                                                                                                                                                                                                                                                                                                        +
                                                                                                                                                                                                                                                                                                                  +
   SELECT jsonb_build_object(                                                                                                                                                                                                                                                                                     +
     'escrow_status', escrow_status,                                                                                                                                                                                                                                                                              +
     'monitoring_type', monitoring_type,                                                                                                                                                                                                                                                                          +
     'total_escrowed', total_escrowed,                                                                                                                                                                                                                                                                            +
     'draw_amount_released', draw_amount_released,                                                                                                                                                                                                                                                                +
     'holdback_amount', holdback_amount                                                                                                                                                                                                                                                                           +
   ) INTO v_new                                                                                                                                                                                                                                                                                                   +
   FROM public.loss_draft_tracking                                                                                                                                                                                                                                                                                +
   WHERE id = p_loss_draft_id;                                                                                                                                                                                                                                                                                    +
                                                                                                                                                                                                                                                                                                                  +
   INSERT INTO public.loss_draft_audit_log (                                                                                                                                                                                                                                                                      +
     loss_draft_id, action_type, actor_id, amount, notes, old_values, new_values                                                                                                                                                                                                                                  +
   ) VALUES (                                                                                                                                                                                                                                                                                                     +
     p_loss_draft_id, p_action, p_actor_id, p_amount, p_notes, v_old, v_new                                                                                                                                                                                                                                       +
   );                                                                                                                                                                                                                                                                                                             +
 END;                                                                                                                                                                                                                                                                                                             +
 $function$                                                                                                                                                                                                                                                                                                       +
 
 CREATE OR REPLACE FUNCTION public.loss_draft_action(p_loss_draft_id uuid, p_action text, p_actor_id uuid, p_amount numeric DEFAULT NULL::numeric, p_tracking_number text DEFAULT NULL::text, p_notes text DEFAULT NULL::text, p_target_status text DEFAULT NULL::text, p_monitoring_type text DEFAULT NULL::text)+
  RETURNS jsonb                                                                                                                                                                                                                                                                                                   +
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                +
  SECURITY DEFINER                                                                                                                                                                                                                                                                                                +
  SET search_path TO 'public'                                                                                                                                                                                                                                                                                     +
 AS $function$                                                                                                                                                                                                                                                                                                    +
 DECLARE                                                                                                                                                                                                                                                                                                          +
   v_old jsonb;                                                                                                                                                                                                                                                                                                   +
   v_new jsonb;                                                                                                                                                                                                                                                                                                   +
   v_check_id uuid;                                                                                                                                                                                                                                                                                               +
 BEGIN                                                                                                                                                                                                                                                                                                            +
   SELECT to_jsonb(ld.*) INTO v_old                                                                                                                                                                                                                                                                               +
   FROM public.loss_draft_tracking ld                                                                                                                                                                                                                                                                             +
   WHERE ld.id = p_loss_draft_id;                                                                                                                                                                                                                                                                                 +
                                                                                                                                                                                                                                                                                                                  +
   IF v_old IS NULL THEN                                                                                                                                                                                                                                                                                          +
     RAISE EXCEPTION 'Loss draft % not found', p_loss_draft_id;                                                                                                                                                                                                                                                   +
   END IF;                                                                                                                                                                                                                                                                                                        +
                                                                                                                                                                                                                                                                                                                  +
   v_check_id := (v_old->>'check_intake_item_id')::uuid;                                                                                                                                                                                                                                                          +
                                                                                                                                                                                                                                                                                                                  +
   IF p_action = 'set_monitoring_type' THEN                                                                                                                                                                                                                                                                       +
     UPDATE public.loss_draft_tracking                                                                                                                                                                                                                                                                            +
       SET monitoring_type = COALESCE(p_monitoring_type, monitoring_type),                                                                                                                                                                                                                                        +
           updated_at = now()                                                                                                                                                                                                                                                                                     +
     WHERE id = p_loss_draft_id;                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                                  +
   ELSIF p_action = 'mark_sent' THEN                                                                                                                                                                                                                                                                              +
     UPDATE public.loss_draft_tracking                                                                                                                                                                                                                                                                            +
       SET escrow_status = 'sent_to_lender',                                                                                                                                                                                                                                                                      +
           check_sent_date = COALESCE(check_sent_date, CURRENT_DATE),                                                                                                                                                                                                                                             +
           tracking_number_sent = COALESCE(p_tracking_number, tracking_number_sent),                                                                                                                                                                                                                              +
           last_contact_at = now(),                                                                                                                                                                                                                                                                               +
           updated_at = now()                                                                                                                                                                                                                                                                                     +
     WHERE id = p_loss_draft_id;                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                                  +
   ELSIF p_action = 'mark_received_back' THEN                                                                                                                                                                                                                                                                     +
     UPDATE public.loss_draft_tracking                                                                                                                                                                                                                                                                            +
       SET escrow_status = 'check_received_back',                                                                                                                                                                                                                                                                 +
           check_received_back_date = COALESCE(check_received_back_date, CURRENT_DATE),                                                                                                                                                                                                                           +
           updated_at = now()                                                                                                                                                                                                                                                                                     +
     WHERE id = p_loss_draft_id;                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                                  +
   ELSIF p_action = 'send_for_endorsements' THEN                                                                                                                                                                                                                                                                  +
     -- Route check back into the Endorsing lane in Check Command Center                                                                                                                                                                                                                                          +
     UPDATE public.loss_draft_tracking                                                                                                                                                                                                                                                                            +
       SET escrow_status = 'endorsing',                                                                                                                                                                                                                                                                           +
           updated_at = now()                                                                                                                                                                                                                                                                                     +
     WHERE id = p_loss_draft_id;                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                                  +
     IF v_check_id IS NOT NULL THEN                                                                                                                                                                                                                                                                               +
       UPDATE public.check_intake_items                                                                                                                                                                                                                                                                           +
         SET status = 'endorsements_in_progress',                                                                                                                                                                                                                                                                 +
             check_stage = 'endorsing',                                                                                                                                                                                                                                                                           +
             updated_at = now()                                                                                                                                                                                                                                                                                   +
       WHERE id = v_check_id;                                                                                                                                                                                                                                                                                     +
     END IF;                                                                                                                                                                                                                                                                                                      +
                                                                                                                                                                                                                                                                                                                  +
   ELSIF p_action = 'mark_escrowed' THEN                                                                                                                                                                                                                                                                          +
     UPDATE public.loss_draft_tracking                                                                                                                                                                                                                                                                            +
       SET escrow_status = 'escrowed',                                                                                                                                                                                                                                                                            +
           total_escrowed = COALESCE(p_amount, total_escrowed),                                                                                                                                                                                                                                                   +
           check_received_date = COALESCE(check_received_date, CURRENT_DATE),                                                                                                                                                                                                                                     +
           updated_at = now()                                                                                                                                                                                                                                                                                     +
     WHERE id = p_loss_draft_id;                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                                  +
   ELSIF p_action = 'request_draw' THEN                                                                                                                                                                                                                                                                           +
     UPDATE public.loss_draft_tracking                                                                                                                                                                                                                                                                            +
       SET escrow_status = 'first_draw_requested',                                                                                                                                                                                                                                                                +
           draw_amount_requested = COALESCE(draw_amount_requested, 0) + COALESCE(p_amount, 0),                                                                                                                                                                                                                    +
           draw_stage = draw_stage + 1,                                                                                                                                                                                                                                                                           +
           updated_at = now()                                                                                                                                                                                                                                                                                     +
     WHERE id = p_loss_draft_id;                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                                  +
   ELSIF p_action = 'record_release' THEN                                                                                                                                                                                                                                                                         +
     UPDATE public.loss_draft_tracking                                                                                                                                                                                                                                                                            +
       SET escrow_status = CASE                                                                                                                                                                                                                                                                                   +
             WHEN COALESCE(draw_amount_released, 0) + COALESCE(p_amount, 0) >= COALESCE(total_escrowed, 0)                                                                                                                                                                                                        +
               AND COALESCE(total_escrowed, 0) > 0                                                                                                                                                                                                                                                                +
             THEN 'final_release_complete'                                                                                                                                                                                                                                                                        +
             ELSE 'partial_release'                                                                                                                                                                                                                                                                               +
           END,                                                                                                                                                                                                                                                                                                   +
           draw_amount_released = COALESCE(draw_amount_released, 0) + COALESCE(p_amount, 0),                                                                                                                                                                                                                      +
           updated_at = now()                                                                                                                                                                                                                                                                                     +
     WHERE id = p_loss_draft_id;                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                                  +
   ELSIF p_action = 'record_holdback' THEN                                                                                                                                                                                                                                                                        +
     UPDATE public.loss_draft_tracking                                                                                                                                                                                                                                                                            +
       SET holdback_amount = COALESCE(p_amount, holdback_amount),                                                                                                                                                                                                                                                 +
           updated_at = now()                                                                                                                                                                                                                                                                                     +
     WHERE id = p_loss_draft_id;                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                                  +
   ELSIF p_action = 'mark_final_release' THEN                                                                                                                                                                                                                                                                     +
     UPDATE public.loss_draft_tracking                                                                                                                                                                                                                                                                            +
       SET escrow_status = 'final_release_complete',                                                                                                                                                                                                                                                              +
           updated_at = now()                                                                                                                                                                                                                                                                                     +
     WHERE id = p_loss_draft_id;                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                                  +
   ELSIF p_action = 'admin_reset_status' THEN                                                                                                                                                                                                                                                                     +
     UPDATE public.loss_draft_tracking                                                                                                                                                                                                                                                                            +
       SET escrow_status = COALESCE(p_target_status, escrow_status),                                                                                                                                                                                                                                              +
           updated_at = now()                                                                                                                                                                                                                                                                                     +
     WHERE id = p_loss_draft_id;                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                                  +
   ELSE                                                                                                                                                                                                                                                                                                           +
     RAISE EXCEPTION 'Unknown loss_draft_action: %', p_action;                                                                                                                                                                                                                                                    +
   END IF;                                                                                                                                                                                                                                                                                                        +
                                                                                                                                                                                                                                                                                                                  +
   SELECT to_jsonb(ld.*) INTO v_new                                                                                                                                                                                                                                                                               +
   FROM public.loss_draft_tracking ld                                                                                                                                                                                                                                                                             +
   WHERE ld.id = p_loss_draft_id;                                                                                                                                                                                                                                                                                 +
                                                                                                                                                                                                                                                                                                                  +
   INSERT INTO public.loss_draft_audit_log (loss_draft_id, action, actor_id, amount, notes, old_values, new_values)                                                                                                                                                                                               +
   VALUES (                                                                                                                                                                                                                                                                                                       +
     p_loss_draft_id,                                                                                                                                                                                                                                                                                             +
     p_action,                                                                                                                                                                                                                                                                                                    +
     p_actor_id,                                                                                                                                                                                                                                                                                                  +
     p_amount,                                                                                                                                                                                                                                                                                                    +
     p_notes,                                                                                                                                                                                                                                                                                                     +
     v_old,                                                                                                                                                                                                                                                                                                       +
     v_new                                                                                                                                                                                                                                                                                                        +
   );                                                                                                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                                                                                  +
   RETURN v_new;                                                                                                                                                                                                                                                                                                  +
 END;                                                                                                                                                                                                                                                                                                             +
 $function$                                                                                                                                                                                                                                                                                                       +
 

