-- Row-count reconciliation for live public base tables (167 including financial_stepup_log).
-- PREPARATION ONLY: do not run against live or staging databases yet.
-- Run the same statement on the source snapshot and the RDS restore, then diff.
-- Table names come from generated types, which match the live base-table count.

SELECT 'ach_authorizations' AS table_name, count(*)::bigint AS row_count FROM public.ach_authorizations
UNION ALL SELECT 'actum_transactions', count(*) FROM public.actum_transactions
UNION ALL SELECT 'ai_response_cache', count(*) FROM public.ai_response_cache
UNION ALL SELECT 'audit_logs', count(*) FROM public.audit_logs
UNION ALL SELECT 'cash_job_attachments', count(*) FROM public.cash_job_attachments
UNION ALL SELECT 'cash_job_line_items', count(*) FROM public.cash_job_line_items
UNION ALL SELECT 'cash_job_payments', count(*) FROM public.cash_job_payments
UNION ALL SELECT 'cash_jobs', count(*) FROM public.cash_jobs
UNION ALL SELECT 'check_audit_log', count(*) FROM public.check_audit_log
UNION ALL SELECT 'check_billing_config', count(*) FROM public.check_billing_config
UNION ALL SELECT 'check_billing_events', count(*) FROM public.check_billing_events
UNION ALL SELECT 'check_cases', count(*) FROM public.check_cases
UNION ALL SELECT 'check_deletion_log', count(*) FROM public.check_deletion_log
UNION ALL SELECT 'check_deposit_image_backfill_queue', count(*) FROM public.check_deposit_image_backfill_queue
UNION ALL SELECT 'check_eligibility_results', count(*) FROM public.check_eligibility_results
UNION ALL SELECT 'check_endorsement_events', count(*) FROM public.check_endorsement_events
UNION ALL SELECT 'check_endorsements', count(*) FROM public.check_endorsements
UNION ALL SELECT 'check_files', count(*) FROM public.check_files
UNION ALL SELECT 'check_intake_items', count(*) FROM public.check_intake_items
UNION ALL SELECT 'check_intake_mortgage_draws', count(*) FROM public.check_intake_mortgage_draws
UNION ALL SELECT 'check_message_reads', count(*) FROM public.check_message_reads
UNION ALL SELECT 'check_messages', count(*) FROM public.check_messages
UNION ALL SELECT 'check_payees', count(*) FROM public.check_payees
UNION ALL SELECT 'check_payment_directions', count(*) FROM public.check_payment_directions
UNION ALL SELECT 'check_reconciliation_alerts', count(*) FROM public.check_reconciliation_alerts
UNION ALL SELECT 'check_reissue_requests', count(*) FROM public.check_reissue_requests
UNION ALL SELECT 'check_review_decisions', count(*) FROM public.check_review_decisions
UNION ALL SELECT 'check_stakeholders', count(*) FROM public.check_stakeholders
UNION ALL SELECT 'check_status_audit', count(*) FROM public.check_status_audit
UNION ALL SELECT 'checkalt_config', count(*) FROM public.checkalt_config
UNION ALL SELECT 'checkalt_deposits', count(*) FROM public.checkalt_deposits
UNION ALL SELECT 'checkalt_tenant_accounts', count(*) FROM public.checkalt_tenant_accounts
UNION ALL SELECT 'checkalt_webhook_events', count(*) FROM public.checkalt_webhook_events
UNION ALL SELECT 'claim_check_mortgage_draws', count(*) FROM public.claim_check_mortgage_draws
UNION ALL SELECT 'claim_check_payments', count(*) FROM public.claim_check_payments
UNION ALL SELECT 'claim_checks', count(*) FROM public.claim_checks
UNION ALL SELECT 'claim_disbursements', count(*) FROM public.claim_disbursements
UNION ALL SELECT 'claim_files', count(*) FROM public.claim_files
UNION ALL SELECT 'claim_folders', count(*) FROM public.claim_folders
UNION ALL SELECT 'claim_operational_state', count(*) FROM public.claim_operational_state
UNION ALL SELECT 'claim_payments', count(*) FROM public.claim_payments
UNION ALL SELECT 'claim_project_plans', count(*) FROM public.claim_project_plans
UNION ALL SELECT 'claim_settlements', count(*) FROM public.claim_settlements
UNION ALL SELECT 'claims', count(*) FROM public.claims
UNION ALL SELECT 'company_branding', count(*) FROM public.company_branding
UNION ALL SELECT 'contractor_profiles', count(*) FROM public.contractor_profiles
UNION ALL SELECT 'contractor_reviews', count(*) FROM public.contractor_reviews
UNION ALL SELECT 'deposit_attachments', count(*) FROM public.deposit_attachments
UNION ALL SELECT 'deposit_audit_log', count(*) FROM public.deposit_audit_log
UNION ALL SELECT 'deposit_automation_runs', count(*) FROM public.deposit_automation_runs
UNION ALL SELECT 'deposit_automation_settings', count(*) FROM public.deposit_automation_settings
UNION ALL SELECT 'deposit_batches', count(*) FROM public.deposit_batches
UNION ALL SELECT 'deposit_daily_digest', count(*) FROM public.deposit_daily_digest
UNION ALL SELECT 'deposit_digest_delivery_log', count(*) FROM public.deposit_digest_delivery_log
UNION ALL SELECT 'deposit_escalation_events', count(*) FROM public.deposit_escalation_events
UNION ALL SELECT 'deposit_escalation_rules', count(*) FROM public.deposit_escalation_rules
UNION ALL SELECT 'deposit_exceptions', count(*) FROM public.deposit_exceptions
UNION ALL SELECT 'deposit_items', count(*) FROM public.deposit_items
UNION ALL SELECT 'deposit_manager_snapshots', count(*) FROM public.deposit_manager_snapshots
UNION ALL SELECT 'deposit_notification_prefs', count(*) FROM public.deposit_notification_prefs
UNION ALL SELECT 'deposit_pending_approvals', count(*) FROM public.deposit_pending_approvals
UNION ALL SELECT 'deposit_provider_attempts', count(*) FROM public.deposit_provider_attempts
UNION ALL SELECT 'deposit_provider_config', count(*) FROM public.deposit_provider_config
UNION ALL SELECT 'deposit_webhook_events', count(*) FROM public.deposit_webhook_events
UNION ALL SELECT 'disbursement_batches', count(*) FROM public.disbursement_batches
UNION ALL SELECT 'disbursement_splits', count(*) FROM public.disbursement_splits
UNION ALL SELECT 'document_templates', count(*) FROM public.document_templates
UNION ALL SELECT 'email_send_log', count(*) FROM public.email_send_log
UNION ALL SELECT 'email_send_state', count(*) FROM public.email_send_state
UNION ALL SELECT 'email_templates', count(*) FROM public.email_templates
UNION ALL SELECT 'email_unsubscribe_tokens', count(*) FROM public.email_unsubscribe_tokens
UNION ALL SELECT 'emails', count(*) FROM public.emails
UNION ALL SELECT 'endorsement_audit_log', count(*) FROM public.endorsement_audit_log
UNION ALL SELECT 'endorsement_automated_reminders', count(*) FROM public.endorsement_automated_reminders
UNION ALL SELECT 'endorsement_requests', count(*) FROM public.endorsement_requests
UNION ALL SELECT 'esign_event_logs', count(*) FROM public.esign_event_logs
UNION ALL SELECT 'external_payment_recipients', count(*) FROM public.external_payment_recipients
UNION ALL SELECT 'financial_stepup_log', count(*) FROM public.financial_stepup_log
UNION ALL SELECT 'glba_security_events', count(*) FROM public.glba_security_events
UNION ALL SELECT 'homeowner_bank_link_tokens', count(*) FROM public.homeowner_bank_link_tokens
UNION ALL SELECT 'homeowner_check_uploads', count(*) FROM public.homeowner_check_uploads
UNION ALL SELECT 'homeowner_deductible_payments', count(*) FROM public.homeowner_deductible_payments
UNION ALL SELECT 'homeowner_directory_leads', count(*) FROM public.homeowner_directory_leads
UNION ALL SELECT 'homeowner_intro_requests', count(*) FROM public.homeowner_intro_requests
UNION ALL SELECT 'homeowner_ledger_check_uploads', count(*) FROM public.homeowner_ledger_check_uploads
UNION ALL SELECT 'homeowner_ledger_events', count(*) FROM public.homeowner_ledger_events
UNION ALL SELECT 'homeowner_ledger_tokens', count(*) FROM public.homeowner_ledger_tokens
UNION ALL SELECT 'loss_draft_audit_log', count(*) FROM public.loss_draft_audit_log
UNION ALL SELECT 'loss_draft_documents', count(*) FROM public.loss_draft_documents
UNION ALL SELECT 'loss_draft_mortgage_intake', count(*) FROM public.loss_draft_mortgage_intake
UNION ALL SELECT 'loss_draft_releases', count(*) FROM public.loss_draft_releases
UNION ALL SELECT 'loss_draft_tracking', count(*) FROM public.loss_draft_tracking
UNION ALL SELECT 'micro_deposit_verifications', count(*) FROM public.micro_deposit_verifications
UNION ALL SELECT 'moov_invoice_customers', count(*) FROM public.moov_invoice_customers
UNION ALL SELECT 'moov_invoices', count(*) FROM public.moov_invoices
UNION ALL SELECT 'mortgage_companies', count(*) FROM public.mortgage_companies
UNION ALL SELECT 'mortgage_desk_config', count(*) FROM public.mortgage_desk_config
UNION ALL SELECT 'mortgage_handling_requests', count(*) FROM public.mortgage_handling_requests
UNION ALL SELECT 'mortgage_releases', count(*) FROM public.mortgage_releases
UNION ALL SELECT 'mortgage_request_library_documents', count(*) FROM public.mortgage_request_library_documents
UNION ALL SELECT 'notification_delivery_logs', count(*) FROM public.notification_delivery_logs
UNION ALL SELECT 'notification_preferences', count(*) FROM public.notification_preferences
UNION ALL SELECT 'notifications', count(*) FROM public.notifications
UNION ALL SELECT 'payment_event_log', count(*) FROM public.payment_event_log
UNION ALL SELECT 'payment_idempotency_keys', count(*) FROM public.payment_idempotency_keys
UNION ALL SELECT 'payment_method_verifications', count(*) FROM public.payment_method_verifications
UNION ALL SELECT 'payment_methods', count(*) FROM public.payment_methods
UNION ALL SELECT 'payment_provider_accounts', count(*) FROM public.payment_provider_accounts
UNION ALL SELECT 'payment_provider_files', count(*) FROM public.payment_provider_files
UNION ALL SELECT 'payment_provider_methods', count(*) FROM public.payment_provider_methods
UNION ALL SELECT 'payment_sweep_configs', count(*) FROM public.payment_sweep_configs
UNION ALL SELECT 'payment_transfer_groups', count(*) FROM public.payment_transfer_groups
UNION ALL SELECT 'payment_transfers', count(*) FROM public.payment_transfers
UNION ALL SELECT 'payment_wallet_ledger', count(*) FROM public.payment_wallet_ledger
UNION ALL SELECT 'payment_wallet_sub_ledgers', count(*) FROM public.payment_wallet_sub_ledgers
UNION ALL SELECT 'payment_wallets', count(*) FROM public.payment_wallets
UNION ALL SELECT 'payment_webhook_events', count(*) FROM public.payment_webhook_events
UNION ALL SELECT 'payroll_runs', count(*) FROM public.payroll_runs
UNION ALL SELECT 'pii_reveal_logs', count(*) FROM public.pii_reveal_logs
UNION ALL SELECT 'plaid_transfer_events', count(*) FROM public.plaid_transfer_events
UNION ALL SELECT 'plaid_webhook_cursors', count(*) FROM public.plaid_webhook_cursors
UNION ALL SELECT 'platform_announcements', count(*) FROM public.platform_announcements
UNION ALL SELECT 'platform_fee_line_items', count(*) FROM public.platform_fee_line_items
UNION ALL SELECT 'platform_fee_occurrences', count(*) FROM public.platform_fee_occurrences
UNION ALL SELECT 'platform_fee_schedules', count(*) FROM public.platform_fee_schedules
UNION ALL SELECT 'privacy_notice_acknowledgments', count(*) FROM public.privacy_notice_acknowledgments
UNION ALL SELECT 'profiles', count(*) FROM public.profiles
UNION ALL SELECT 'recipient_tax_profiles', count(*) FROM public.recipient_tax_profiles
UNION ALL SELECT 'referral_alerts', count(*) FROM public.referral_alerts
UNION ALL SELECT 'referral_events', count(*) FROM public.referral_events
UNION ALL SELECT 'referrers', count(*) FROM public.referrers
UNION ALL SELECT 'role_version_tracker', count(*) FROM public.role_version_tracker
UNION ALL SELECT 'shared_check_messages', count(*) FROM public.shared_check_messages
UNION ALL SELECT 'shared_checks', count(*) FROM public.shared_checks
UNION ALL SELECT 'signature_document_presets', count(*) FROM public.signature_document_presets
UNION ALL SELECT 'signature_field_templates', count(*) FROM public.signature_field_templates
UNION ALL SELECT 'signature_field_values', count(*) FROM public.signature_field_values
UNION ALL SELECT 'signature_fields', count(*) FROM public.signature_fields
UNION ALL SELECT 'signature_requests', count(*) FROM public.signature_requests
UNION ALL SELECT 'signature_signers', count(*) FROM public.signature_signers
UNION ALL SELECT 'sms_messages', count(*) FROM public.sms_messages
UNION ALL SELECT 'spatial_ref_sys', count(*) FROM public.spatial_ref_sys
UNION ALL SELECT 'stakeholder_account_verification_log', count(*) FROM public.stakeholder_account_verification_log
UNION ALL SELECT 'stakeholder_accounts', count(*) FROM public.stakeholder_accounts
UNION ALL SELECT 'stakeholder_limit_requests', count(*) FROM public.stakeholder_limit_requests
UNION ALL SELECT 'storage_backup_log', count(*) FROM public.storage_backup_log
UNION ALL SELECT 'suppressed_emails', count(*) FROM public.suppressed_emails
UNION ALL SELECT 'tenant_bank_accounts', count(*) FROM public.tenant_bank_accounts
UNION ALL SELECT 'tenant_billing_accounts', count(*) FROM public.tenant_billing_accounts
UNION ALL SELECT 'tenant_credit_balances', count(*) FROM public.tenant_credit_balances
UNION ALL SELECT 'tenant_credit_transactions', count(*) FROM public.tenant_credit_transactions
UNION ALL SELECT 'tenant_documents', count(*) FROM public.tenant_documents
UNION ALL SELECT 'tenant_email_settings', count(*) FROM public.tenant_email_settings
UNION ALL SELECT 'tenant_maintenance_payments', count(*) FROM public.tenant_maintenance_payments
UNION ALL SELECT 'tenant_openai_credentials', count(*) FROM public.tenant_openai_credentials
UNION ALL SELECT 'tenant_partner_code_aliases', count(*) FROM public.tenant_partner_code_aliases
UNION ALL SELECT 'tenant_partnerships', count(*) FROM public.tenant_partnerships
UNION ALL SELECT 'tenant_usage_logs', count(*) FROM public.tenant_usage_logs
UNION ALL SELECT 'tenant_users', count(*) FROM public.tenant_users
UNION ALL SELECT 'tenant_vetting_documents', count(*) FROM public.tenant_vetting_documents
UNION ALL SELECT 'tenant_wallet_funding_settings', count(*) FROM public.tenant_wallet_funding_settings
UNION ALL SELECT 'tenants', count(*) FROM public.tenants
UNION ALL SELECT 'user_roles', count(*) FROM public.user_roles
UNION ALL SELECT 'user_sessions', count(*) FROM public.user_sessions
UNION ALL SELECT 'wallet_funding_queue', count(*) FROM public.wallet_funding_queue
UNION ALL SELECT 'wallet_funding_requests', count(*) FROM public.wallet_funding_requests
UNION ALL SELECT 'zip_geocache', count(*) FROM public.zip_geocache
ORDER BY table_name;
