ALTER TABLE public.homeowner_ledger_events
  DROP CONSTRAINT IF EXISTS homeowner_ledger_events_event_type_check;

ALTER TABLE public.homeowner_ledger_events
  ADD CONSTRAINT homeowner_ledger_events_event_type_check
  CHECK (event_type = ANY (ARRAY[
    'check_received','endorsement_requested','endorsement_signed','endorsements_sent',
    'ready_for_deposit','loss_draft_routing','deposited','cleared','funds_released',
    'production_projected','production_confirmed','production_doc_uploaded',
    'supplement_check','depreciation_check','deductible_check',
    'homeowner_check_upload','homeowner_upload_attached',
    'document_sent','document_uploaded','document_signed_all',
    'mortgage_check_sent','mortgage_check_returned','mortgage_followup','mortgage_update',
    'contractor_upload','ops_note'
  ]));

CREATE OR REPLACE FUNCTION public.mirror_loss_draft_upload_to_ledger()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_claim uuid;
  v_tenant uuid;
  v_actor text;
  v_event_type text;
  v_file_added boolean;
  v_newly_signed boolean;
BEGIN
  v_file_added := NEW.file_path IS NOT NULL AND (TG_OP = 'INSERT' OR OLD.file_path IS DISTINCT FROM NEW.file_path);
  v_newly_signed := NEW.signature_status = 'signed' AND (TG_OP = 'INSERT' OR OLD.signature_status IS DISTINCT FROM NEW.signature_status);

  IF NOT v_file_added AND NOT v_newly_signed THEN
    RETURN NEW;
  END IF;

  SELECT ld.claim_id, ld.tenant_id
    INTO v_claim, v_tenant
  FROM public.loss_draft_tracking ld
  WHERE ld.id = NEW.loss_draft_id;

  IF v_claim IS NULL THEN
    RETURN NEW;
  END IF;

  v_event_type := CASE WHEN v_newly_signed THEN 'document_signed_all' ELSE 'document_uploaded' END;
  v_actor := CASE
    WHEN v_newly_signed THEN 'Signed document filed'
    WHEN NEW.is_template_generated THEN 'Document generated by ChecksOps'
    ELSE 'Document uploaded'
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM public.homeowner_ledger_events hle
    WHERE hle.claim_id = v_claim
      AND hle.event_type = v_event_type
      AND hle.payload_json->>'loss_draft_document_id' = NEW.id::text
  ) THEN
    INSERT INTO public.homeowner_ledger_events (
      tenant_id, claim_id, event_type, occurred_at, actor_label, payload_json
    ) VALUES (
      v_tenant, v_claim, v_event_type,
      COALESCE(NEW.submitted_at, NEW.signed_at, now()),
      v_actor,
      jsonb_build_object(
        'loss_draft_document_id', NEW.id,
        'document_label', NEW.document_label,
        'document_type',  NEW.document_type,
        'document_name',  COALESCE(NEW.file_name, NEW.document_label),
        'file_name',      NEW.file_name,
        'note',           NEW.notes
      )
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_mirror_loss_draft_upload ON public.loss_draft_documents;
CREATE TRIGGER trg_mirror_loss_draft_upload
AFTER INSERT OR UPDATE OF file_path, signature_status, submitted_at ON public.loss_draft_documents
FOR EACH ROW EXECUTE FUNCTION public.mirror_loss_draft_upload_to_ledger();

CREATE OR REPLACE FUNCTION public.mirror_check_file_to_homeowner_ledger()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_claim uuid;
  v_tenant uuid;
  v_check_number text;
  v_event_type text;
  v_actor text;
BEGIN
  SELECT cii.claim_id, cii.tenant_id, cii.check_number
    INTO v_claim, v_tenant, v_check_number
  FROM public.check_intake_items cii
  WHERE cii.id = NEW.check_intake_item_id;

  IF v_claim IS NULL OR v_tenant IS NULL THEN
    RETURN NEW;
  END IF;

  v_event_type := CASE
    WHEN lower(COALESCE(NEW.source, '')) LIKE '%contractor%' THEN 'contractor_upload'
    ELSE 'document_uploaded'
  END;

  v_actor := CASE
    WHEN NEW.signature_request_id IS NOT NULL OR NEW.category IN ('signed_dtp', 'signed_document') THEN 'Signed document filed'
    WHEN NEW.source = 'mortgage_ops' THEN 'Mortgage Ops uploaded document'
    WHEN lower(COALESCE(NEW.source, '')) LIKE '%contractor%' THEN 'Contractor uploaded document'
    ELSE 'Document uploaded'
  END;

  IF NOT EXISTS (
    SELECT 1 FROM public.homeowner_ledger_events hle
    WHERE hle.payload_json->>'check_file_id' = NEW.id::text
      AND hle.event_type = v_event_type
  ) THEN
    INSERT INTO public.homeowner_ledger_events (
      tenant_id, claim_id, check_id, event_type, occurred_at, actor_label, payload_json, created_by
    ) VALUES (
      v_tenant, v_claim, NEW.check_intake_item_id, v_event_type, COALESCE(NEW.created_at, now()), v_actor,
      jsonb_build_object(
        'check_file_id', NEW.id,
        'document_name', NEW.file_name,
        'document_label', COALESCE(NULLIF(NEW.description, ''), NEW.file_name),
        'file_name', NEW.file_name,
        'category', NEW.category,
        'source', NEW.source,
        'check_number', v_check_number,
        'note', NEW.description
      ),
      NEW.uploaded_by
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_mirror_check_file_to_homeowner_ledger ON public.check_files;
CREATE TRIGGER trg_mirror_check_file_to_homeowner_ledger
AFTER INSERT ON public.check_files
FOR EACH ROW EXECUTE FUNCTION public.mirror_check_file_to_homeowner_ledger();

CREATE OR REPLACE FUNCTION public.mirror_check_message_to_homeowner_ledger()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_claim uuid;
  v_tenant uuid;
  v_check_number text;
  v_actor text;
BEGIN
  IF COALESCE(NEW.is_deleted, false) OR NULLIF(trim(COALESCE(NEW.body, '')), '') IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT cii.claim_id, cii.tenant_id, cii.check_number
    INTO v_claim, v_tenant, v_check_number
  FROM public.check_intake_items cii
  WHERE cii.id = NEW.check_id;

  IF v_claim IS NULL OR v_tenant IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT COALESCE(NULLIF(p.full_name, ''), p.email, 'Team note')
    INTO v_actor
  FROM public.profiles p
  WHERE p.id = NEW.sender_id;

  INSERT INTO public.homeowner_ledger_events (
    tenant_id, claim_id, check_id, event_type, occurred_at, actor_label, payload_json, created_by
  ) VALUES (
    v_tenant, v_claim, NEW.check_id, 'ops_note', COALESCE(NEW.created_at, now()), COALESCE(v_actor, 'Team note'),
    jsonb_build_object(
      'check_message_id', NEW.id,
      'note', NEW.body,
      'check_number', v_check_number
    ),
    NEW.sender_id
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_mirror_check_message_to_homeowner_ledger ON public.check_messages;
CREATE TRIGGER trg_mirror_check_message_to_homeowner_ledger
AFTER INSERT ON public.check_messages
FOR EACH ROW EXECUTE FUNCTION public.mirror_check_message_to_homeowner_ledger();

CREATE OR REPLACE FUNCTION public.mirror_signature_request_to_homeowner_ledger()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_claim uuid;
  v_tenant uuid;
  v_check_id uuid;
BEGIN
  IF NEW.claim_id IS NOT NULL THEN
    SELECT c.id, c.tenant_id INTO v_claim, v_tenant
    FROM public.claims c
    WHERE c.id = NEW.claim_id;
  ELSIF NEW.check_intake_item_id IS NOT NULL THEN
    SELECT cii.claim_id, cii.tenant_id, cii.id INTO v_claim, v_tenant, v_check_id
    FROM public.check_intake_items cii
    WHERE cii.id = NEW.check_intake_item_id;
  END IF;

  IF v_claim IS NULL OR v_tenant IS NULL THEN
    RETURN NEW;
  END IF;

  IF v_check_id IS NULL THEN
    SELECT lt.check_intake_item_id INTO v_check_id
    FROM public.loss_draft_tracking lt
    WHERE lt.claim_id = v_claim
    ORDER BY lt.created_at DESC
    LIMIT 1;
  END IF;

  IF NEW.sent_at IS NOT NULL
     AND (TG_OP = 'INSERT' OR OLD.sent_at IS DISTINCT FROM NEW.sent_at OR OLD.status IS DISTINCT FROM NEW.status)
     AND NOT EXISTS (
       SELECT 1 FROM public.homeowner_ledger_events hle
       WHERE hle.claim_id = v_claim
         AND hle.event_type = 'document_sent'
         AND hle.payload_json->>'signature_request_id' = NEW.id::text
     ) THEN
    INSERT INTO public.homeowner_ledger_events (
      tenant_id, claim_id, check_id, event_type, occurred_at, actor_label, payload_json
    ) VALUES (
      v_tenant, v_claim, v_check_id, 'document_sent', NEW.sent_at, 'Document sent for signature',
      jsonb_build_object(
        'signature_request_id', NEW.id,
        'document_name', NEW.document_name,
        'document_label', NEW.document_name,
        'status', NEW.status
      )
    );
  END IF;

  IF (NEW.completed_at IS NOT NULL OR NEW.status = 'completed')
     AND (TG_OP = 'INSERT' OR OLD.completed_at IS DISTINCT FROM NEW.completed_at OR OLD.status IS DISTINCT FROM NEW.status)
     AND NOT EXISTS (
       SELECT 1 FROM public.homeowner_ledger_events hle
       WHERE hle.claim_id = v_claim
         AND hle.event_type = 'document_signed_all'
         AND hle.payload_json->>'signature_request_id' = NEW.id::text
     ) THEN
    INSERT INTO public.homeowner_ledger_events (
      tenant_id, claim_id, check_id, event_type, occurred_at, actor_label, payload_json
    ) VALUES (
      v_tenant, v_claim, v_check_id, 'document_signed_all', COALESCE(NEW.completed_at, now()), 'Document fully signed',
      jsonb_build_object(
        'signature_request_id', NEW.id,
        'document_name', NEW.document_name,
        'document_label', NEW.document_name,
        'status', NEW.status
      )
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_mirror_signature_request_to_homeowner_ledger ON public.signature_requests;
CREATE TRIGGER trg_mirror_signature_request_to_homeowner_ledger
AFTER INSERT OR UPDATE OF sent_at, status, completed_at ON public.signature_requests
FOR EACH ROW EXECUTE FUNCTION public.mirror_signature_request_to_homeowner_ledger();

CREATE OR REPLACE FUNCTION public.mirror_signature_signer_to_homeowner_ledger()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_req record;
  v_claim uuid;
  v_tenant uuid;
  v_check_id uuid;
BEGIN
  IF NEW.status <> 'signed' OR (TG_OP = 'UPDATE' AND OLD.status IS NOT DISTINCT FROM NEW.status) THEN
    RETURN NEW;
  END IF;

  SELECT sr.id, sr.claim_id, sr.check_intake_item_id, sr.document_name
    INTO v_req
  FROM public.signature_requests sr
  WHERE sr.id = NEW.signature_request_id;

  IF v_req.claim_id IS NOT NULL THEN
    SELECT c.id, c.tenant_id INTO v_claim, v_tenant
    FROM public.claims c
    WHERE c.id = v_req.claim_id;
  ELSIF v_req.check_intake_item_id IS NOT NULL THEN
    SELECT cii.claim_id, cii.tenant_id, cii.id INTO v_claim, v_tenant, v_check_id
    FROM public.check_intake_items cii
    WHERE cii.id = v_req.check_intake_item_id;
  END IF;

  IF v_claim IS NULL OR v_tenant IS NULL THEN
    RETURN NEW;
  END IF;

  IF v_check_id IS NULL THEN
    SELECT lt.check_intake_item_id INTO v_check_id
    FROM public.loss_draft_tracking lt
    WHERE lt.claim_id = v_claim
    ORDER BY lt.created_at DESC
    LIMIT 1;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.homeowner_ledger_events hle
    WHERE hle.claim_id = v_claim
      AND hle.event_type = 'endorsement_signed'
      AND hle.payload_json->>'signer_id' = NEW.id::text
  ) THEN
    INSERT INTO public.homeowner_ledger_events (
      tenant_id, claim_id, check_id, event_type, occurred_at, actor_label, payload_json
    ) VALUES (
      v_tenant, v_claim, v_check_id, 'endorsement_signed', COALESCE(NEW.signed_at, now()), NEW.signer_name,
      jsonb_build_object(
        'signature_request_id', NEW.signature_request_id,
        'signer_id', NEW.id,
        'signer_name', NEW.signer_name,
        'signer_email', NEW.signer_email,
        'document_name', v_req.document_name,
        'document_label', v_req.document_name
      )
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_mirror_signature_signer_to_homeowner_ledger ON public.signature_signers;
CREATE TRIGGER trg_mirror_signature_signer_to_homeowner_ledger
AFTER INSERT OR UPDATE OF status, signed_at ON public.signature_signers
FOR EACH ROW EXECUTE FUNCTION public.mirror_signature_signer_to_homeowner_ledger();