
-- Widen event_type check
ALTER TABLE public.homeowner_ledger_events
  DROP CONSTRAINT IF EXISTS homeowner_ledger_events_event_type_check;

ALTER TABLE public.homeowner_ledger_events
  ADD CONSTRAINT homeowner_ledger_events_event_type_check
  CHECK (event_type = ANY (ARRAY[
    'check_received','endorsement_requested','endorsement_signed','endorsements_sent',
    'ready_for_deposit','loss_draft_routing','deposited','cleared','funds_released',
    'production_projected','production_confirmed','production_doc_uploaded',
    'supplement_check','depreciation_check','deductible_check',
    'homeowner_check_upload','homeowner_upload_attached',
    'document_uploaded','document_signed_all',
    'mortgage_check_sent','mortgage_check_returned','mortgage_followup','mortgage_update',
    'contractor_upload','ops_note'
  ]));

-- Trigger: loss_draft_documents file uploaded/attached -> homeowner timeline
CREATE OR REPLACE FUNCTION public.mirror_loss_draft_upload_to_ledger()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_claim uuid;
  v_tenant uuid;
  v_actor text;
BEGIN
  -- Only mirror when a file_path transitions to non-null (upload/attach)
  IF NEW.file_path IS NULL THEN
    RETURN NEW;
  END IF;
  IF TG_OP = 'UPDATE' AND OLD.file_path IS NOT DISTINCT FROM NEW.file_path THEN
    RETURN NEW;
  END IF;

  SELECT ld.claim_id, ld.tenant_id
    INTO v_claim, v_tenant
  FROM public.loss_draft_tracking ld
  WHERE ld.id = NEW.loss_draft_id;

  IF v_claim IS NULL THEN
    RETURN NEW;
  END IF;

  v_actor := CASE
    WHEN NEW.signature_status = 'signed' THEN 'Signed document filed'
    WHEN NEW.is_template_generated THEN 'Document generated by ChecksOps'
    ELSE 'Document uploaded'
  END;

  INSERT INTO public.homeowner_ledger_events (
    tenant_id, claim_id, event_type, occurred_at, actor_label, payload_json
  ) VALUES (
    v_tenant, v_claim,
    CASE WHEN NEW.signature_status = 'signed' THEN 'document_signed_all' ELSE 'document_uploaded' END,
    now(), v_actor,
    jsonb_build_object(
      'document_label', NEW.document_label,
      'document_type',  NEW.document_type,
      'file_name',      NEW.file_name
    )
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_mirror_loss_draft_upload ON public.loss_draft_documents;
CREATE TRIGGER trg_mirror_loss_draft_upload
AFTER INSERT OR UPDATE OF file_path, signature_status ON public.loss_draft_documents
FOR EACH ROW EXECUTE FUNCTION public.mirror_loss_draft_upload_to_ledger();

-- Trigger: mortgage_handling_requests date fields -> homeowner timeline
CREATE OR REPLACE FUNCTION public.mirror_mortgage_dates_to_ledger()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_claim uuid;
BEGIN
  SELECT claim_id INTO v_claim FROM public.claims WHERE id = NEW.claim_id;
  IF v_claim IS NULL THEN v_claim := NEW.claim_id; END IF;
  IF NEW.claim_id IS NULL THEN RETURN NEW; END IF;

  IF NEW.check_sent_date IS DISTINCT FROM OLD.check_sent_date AND NEW.check_sent_date IS NOT NULL THEN
    INSERT INTO public.homeowner_ledger_events (
      tenant_id, claim_id, event_type, occurred_at, actor_label, payload_json
    ) VALUES (
      NEW.tenant_id, NEW.claim_id, 'mortgage_check_sent', NEW.check_sent_date,
      'Check sent to ' || COALESCE(NEW.mortgage_company, 'mortgage company'),
      jsonb_build_object('mortgage_company', NEW.mortgage_company)
    );
  END IF;

  IF NEW.check_received_back_date IS DISTINCT FROM OLD.check_received_back_date AND NEW.check_received_back_date IS NOT NULL THEN
    INSERT INTO public.homeowner_ledger_events (
      tenant_id, claim_id, event_type, occurred_at, actor_label, payload_json
    ) VALUES (
      NEW.tenant_id, NEW.claim_id, 'mortgage_check_returned', NEW.check_received_back_date,
      'Endorsed check returned from ' || COALESCE(NEW.mortgage_company, 'mortgage company'),
      jsonb_build_object('mortgage_company', NEW.mortgage_company)
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_mirror_mortgage_dates ON public.mortgage_handling_requests;
CREATE TRIGGER trg_mirror_mortgage_dates
AFTER UPDATE OF check_sent_date, check_received_back_date ON public.mortgage_handling_requests
FOR EACH ROW EXECUTE FUNCTION public.mirror_mortgage_dates_to_ledger();
