import {
  AlertTriangle,
  CalendarClock,
  FileCheck2,
  KeyRound,
  Landmark,
  ShieldCheck,
  Users,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { TenantAgreementsAcceptances, type TenantAgreementAcceptance } from "./TenantAgreementsAcceptances";
import { TenantAuditActivity, type TenantAuditEvent } from "./TenantAuditActivity";
import { TenantComplianceReviews, type TenantComplianceReview } from "./TenantComplianceReviews";
import { TenantComplianceIssues, type TenantComplianceIssue } from "./TenantComplianceIssues";
import { TenantComplianceDocuments, type TenantComplianceDocument } from "./TenantComplianceDocuments";
import { TenantComplianceTimeline, type TenantComplianceTimelineEvent } from "./TenantComplianceTimeline";

export type ComplianceStatus = "Compliant" | "Action Required" | "Review Due" | "Restricted" | "Pending";
export interface TenantComplianceOverview { securityStatus: ComplianceStatus; usersAndAccess: ComplianceStatus; mfaEnrollment: ComplianceStatus; agreementsAndPolicies: ComplianceStatus; complianceIssues: ComplianceStatus; nextReview: ComplianceStatus; actionItems: string[]; }
export interface TenantAccessRecord { id: string; name: string; email: string; role: string; accountStatus: string; accessLevel: string; financialAccess: boolean; totpEnrolled: boolean; passkeyEnrolled: boolean; accessGrantedAt?: string; lastLoginAt?: string; lastAccessReviewAt?: string; accessRevokedAt?: string; }
export type FinancialPermissionKey = "viewCheckImages" | "viewBankingInformation" | "submitDeposits" | "approveDisbursements" | "changeBankAccounts" | "manageMoov" | "manageCheckAlt" | "manageTenantUsers" | "exportFinancialData";
export interface TenantFinancialPermissions { userId: string; userName: string; role: string; permissions: Record<FinancialPermissionKey, boolean>; }
export interface TenantSecurityReadiness { userId: string; userName: string; email: string; loginMethod: "Passkey" | "Magic Link" | "Pending"; totpEnrolled: boolean; passkeyEnrolled: boolean; financialActionsEnabled: boolean; stepUpRequired: boolean; actionRequired?: string; }
export interface TenantSecurityComplianceViewProps { tenantId: string; tenantName: string; overview?: TenantComplianceOverview; accessRecords?: TenantAccessRecord[]; financialPermissions?: TenantFinancialPermissions[]; securityReadiness?: TenantSecurityReadiness[]; agreementAcceptances?: TenantAgreementAcceptance[]; auditEvents?: TenantAuditEvent[]; complianceReviews?: TenantComplianceReview[]; complianceIssues?: TenantComplianceIssue[]; complianceDocuments?: TenantComplianceDocument[]; complianceTimelineEvents?: TenantComplianceTimelineEvent[]; onViewAccess?: (record: TenantAccessRecord) => void; onEditPermissions?: (record: TenantAccessRecord) => void; onRestrictFinancialAccess?: (record: TenantAccessRecord) => void; onRevokeAccess?: (record: TenantAccessRecord) => void; onRequireSecuritySetup?: (record: TenantAccessRecord) => void; onEditFinancialPermissions?: (record: TenantFinancialPermissions) => void; onSendSecuritySetup?: (record: TenantSecurityReadiness) => void; }
const placeholderOverview: TenantComplianceOverview = { securityStatus: "Pending", usersAndAccess: "Pending", mfaEnrollment: "Pending", agreementsAndPolicies: "Pending", complianceIssues: "Pending", nextReview: "Pending", actionItems: ["Compliance data will populate when the AWS compliance API is connected."] };
const statusClasses: Record<ComplianceStatus, string> = { Compliant: "border-emerald-500/30 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400", "Action Required": "border-amber-500/30 bg-amber-500/10 text-amber-700 dark:text-amber-400", "Review Due": "border-orange-500/30 bg-orange-500/10 text-orange-700 dark:text-orange-400", Restricted: "border-destructive/30 bg-destructive/10 text-destructive", Pending: "border-border bg-muted text-muted-foreground" };
const financialPermissionLabels: Record<FinancialPermissionKey, string> = { viewCheckImages: "Check Images", viewBankingInformation: "Banking Info", submitDeposits: "Submit Deposits", approveDisbursements: "Approve Disbursements", changeBankAccounts: "Bank Changes", manageMoov: "Moov", manageCheckAlt: "CheckAlt", manageTenantUsers: "Tenant Users", exportFinancialData: "Exports" };
const formatDate = (value?: string) => { if (!value) return "—"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString(); };
const yesNoBadge = (ready: boolean, yesLabel: string, noLabel: string) => <Badge variant="outline" className={ready ? statusClasses.Compliant : statusClasses["Action Required"]}>{ready ? yesLabel : noLabel}</Badge>;

export function TenantSecurityComplianceView({ tenantId, tenantName, overview = placeholderOverview, accessRecords = [], financialPermissions = [], securityReadiness = [], agreementAcceptances = [], auditEvents = [], complianceReviews = [], complianceIssues = [], complianceDocuments = [], complianceTimelineEvents = [], onViewAccess, onEditPermissions, onRestrictFinancialAccess, onRevokeAccess, onRequireSecuritySetup, onEditFinancialPermissions, onSendSecuritySetup }: TenantSecurityComplianceViewProps) {
  const cards = [
    { label: "Security Status", status: overview.securityStatus, icon: ShieldCheck }, { label: "Users & Access", status: overview.usersAndAccess, icon: Users },
    { label: "MFA Enrollment", status: overview.mfaEnrollment, icon: KeyRound }, { label: "Agreements & Policies", status: overview.agreementsAndPolicies, icon: FileCheck2 },
    { label: "Compliance Issues", status: overview.complianceIssues, icon: AlertTriangle }, { label: "Next Review", status: overview.nextReview, icon: CalendarClock },
  ];
  return <div className="space-y-6" data-tenant-id={tenantId}>
    <div><h3 className="text-lg font-semibold">Security & Compliance</h3><p className="text-sm text-muted-foreground">Tenant-specific security, access, agreements, and compliance readiness for {tenantName}.</p></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{cards.map(({ label, status, icon: Icon }) => <Card key={label}><CardContent className="flex items-center justify-between gap-4 p-4"><div className="flex min-w-0 items-center gap-3"><div className="rounded-lg border border-border bg-muted/40 p-2"><Icon className="h-4 w-4 text-muted-foreground" /></div><div><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-1 text-sm font-semibold">{status}</p></div></div><Badge variant="outline" className={statusClasses[status]}>{status}</Badge></CardContent></Card>)}</div>
    <Card><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><AlertTriangle className="h-4 w-4" /> Compliance Health</CardTitle></CardHeader><CardContent className="space-y-3">{overview.actionItems.length === 0 ? <div className="flex items-center gap-2 rounded-lg border border-emerald-500/20 bg-emerald-500/5 p-3 text-sm"><ShieldCheck className="h-4 w-4" /> No outstanding tenant compliance actions.</div> : overview.actionItems.map((item, index) => <div key={`${item}-${index}`} className="flex items-start gap-3 rounded-lg border border-border bg-muted/20 p-3"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-500" /><div><p className="text-sm font-medium">Action Required</p><p className="text-sm text-muted-foreground">{item}</p></div></div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Users className="h-4 w-4" /> Users & Access / ACL</CardTitle></CardHeader><CardContent>{accessRecords.length === 0 ? <div className="rounded-lg border border-dashed border-border p-6 text-center"><p className="text-sm font-medium">No AWS access-control records connected yet.</p><p className="mt-1 text-xs text-muted-foreground">This table is ready for the tenant ACL API. Existing Supabase authorization is not modified.</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead className="border-b text-left text-xs text-muted-foreground"><tr><th className="px-3 py-2">User</th><th className="px-3 py-2">Role</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Access</th><th className="px-3 py-2">Financial</th><th className="px-3 py-2">TOTP</th><th className="px-3 py-2">Passkey</th><th className="px-3 py-2">Granted</th><th className="px-3 py-2">Last Login</th><th className="px-3 py-2">Last Review</th><th className="px-3 py-2">Actions</th></tr></thead><tbody className="divide-y divide-border">{accessRecords.map(record => <tr key={record.id}><td className="px-3 py-3"><p className="font-medium">{record.name}</p><p className="text-xs text-muted-foreground">{record.email}</p></td><td className="px-3 py-3">{record.role}</td><td className="px-3 py-3"><Badge variant="outline">{record.accountStatus}</Badge></td><td className="px-3 py-3">{record.accessLevel}</td><td className="px-3 py-3">{record.financialAccess ? "Enabled" : "Restricted"}</td><td className="px-3 py-3">{record.totpEnrolled ? "Enrolled" : "Required"}</td><td className="px-3 py-3">{record.passkeyEnrolled ? "Enrolled" : "Not enrolled"}</td><td className="px-3 py-3 text-xs">{formatDate(record.accessGrantedAt)}</td><td className="px-3 py-3 text-xs">{formatDate(record.lastLoginAt)}</td><td className="px-3 py-3 text-xs">{formatDate(record.lastAccessReviewAt)}</td><td className="px-3 py-3"><div className="flex flex-wrap gap-1"><Button size="sm" variant="outline" onClick={() => onViewAccess?.(record)} disabled={!onViewAccess}>View</Button><Button size="sm" variant="outline" onClick={() => onEditPermissions?.(record)} disabled={!onEditPermissions}>Permissions</Button><Button size="sm" variant="outline" onClick={() => onRestrictFinancialAccess?.(record)} disabled={!onRestrictFinancialAccess}>Restrict Financial</Button><Button size="sm" variant="outline" onClick={() => onRequireSecuritySetup?.(record)} disabled={!onRequireSecuritySetup}>Require Security</Button><Button size="sm" variant="destructive" onClick={() => onRevokeAccess?.(record)} disabled={!onRevokeAccess}>Revoke</Button></div></td></tr>)}</tbody></table></div>}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Landmark className="h-4 w-4" /> Financial Access</CardTitle></CardHeader><CardContent className="space-y-4"><div className="rounded-lg border border-amber-500/20 bg-amber-500/5 p-3"><p className="text-sm font-medium">Backend-enforced permissions</p><p className="mt-1 text-xs text-muted-foreground">AWS must validate tenant, user, role, MFA/step-up state, and permission on every protected request. Hiding a button is never authorization.</p></div>{financialPermissions.length === 0 ? <div className="rounded-lg border border-dashed border-border p-6 text-center"><p className="text-sm font-medium">No financial permission records connected yet.</p><p className="mt-1 text-xs text-muted-foreground">Ready for the AWS authorization API. No current Moov, CheckAlt, bank, deposit, or disbursement behavior is changed.</p></div> : <div className="space-y-3">{financialPermissions.map(record => <div key={record.userId} className="rounded-lg border border-border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium">{record.userName}</p><p className="text-xs text-muted-foreground">{record.role}</p></div><Button size="sm" variant="outline" onClick={() => onEditFinancialPermissions?.(record)} disabled={!onEditFinancialPermissions}>Edit Financial Permissions</Button></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{(Object.keys(financialPermissionLabels) as FinancialPermissionKey[]).map(key => <div key={key} className="flex items-center justify-between rounded-md border border-border bg-muted/20 px-3 py-2"><span className="text-xs font-medium">{financialPermissionLabels[key]}</span><Badge variant="outline" className={record.permissions[key] ? statusClasses.Compliant : statusClasses.Pending}>{record.permissions[key] ? "Allowed" : "Denied"}</Badge></div>)}</div></div>)}</div>}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><KeyRound className="h-4 w-4" /> Security Requirements</CardTitle></CardHeader><CardContent className="space-y-4"><div className="rounded-lg border border-border bg-muted/20 p-3"><p className="text-sm font-medium">Financial actions require security readiness</p><p className="mt-1 text-xs text-muted-foreground">Target state: passkey or magic-link login, TOTP enrollment before financial access, and step-up authentication on every check deposit or disbursement submission. AWS will be the source of truth.</p></div>{securityReadiness.length === 0 ? <div className="rounded-lg border border-dashed border-border p-6 text-center"><p className="text-sm font-medium">No AWS authentication-readiness records connected yet.</p><p className="mt-1 text-xs text-muted-foreground">The interface is ready for Cognito/AWS authentication status without changing the current login system.</p></div> : <div className="space-y-3">{securityReadiness.map(record => { const ready = record.totpEnrolled && record.financialActionsEnabled && record.stepUpRequired; return <div key={record.userId} className="rounded-lg border border-border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">{record.userName}</p><p className="text-xs text-muted-foreground">{record.email}</p></div><Badge variant="outline" className={ready ? statusClasses.Compliant : statusClasses["Action Required"]}>{ready ? "Ready" : "Action Required"}</Badge></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-5"><div className="rounded-md border p-3"><p className="text-xs text-muted-foreground">Login Method</p><p className="mt-1 text-sm font-medium">{record.loginMethod}</p></div><div className="rounded-md border p-3"><p className="text-xs text-muted-foreground">TOTP</p><div className="mt-1">{yesNoBadge(record.totpEnrolled, "Enrolled", "Required")}</div></div><div className="rounded-md border p-3"><p className="text-xs text-muted-foreground">Passkey</p><div className="mt-1">{yesNoBadge(record.passkeyEnrolled, "Enrolled", "Not enrolled")}</div></div><div className="rounded-md border p-3"><p className="text-xs text-muted-foreground">Financial Actions</p><div className="mt-1">{yesNoBadge(record.financialActionsEnabled, "Enabled", "Disabled")}</div></div><div className="rounded-md border p-3"><p className="text-xs text-muted-foreground">Step-Up</p><div className="mt-1">{yesNoBadge(record.stepUpRequired, "Required", "Not configured")}</div></div></div>{record.actionRequired && <div className="mt-3 flex flex-wrap items-center justify-between gap-3 rounded-md border border-amber-500/20 bg-amber-500/5 p-3"><p className="text-xs text-muted-foreground">{record.actionRequired}</p><Button size="sm" variant="outline" onClick={() => onSendSecuritySetup?.(record)} disabled={!onSendSecuritySetup}>Require Security Setup</Button></div>}</div>; })}</div>}</CardContent></Card>
    <TenantAgreementsAcceptances records={agreementAcceptances} />
    <TenantAuditActivity events={auditEvents} />
    <TenantComplianceReviews reviews={complianceReviews} />
    <TenantComplianceIssues issues={complianceIssues} />
    <TenantComplianceDocuments documents={complianceDocuments} />
    <TenantComplianceTimeline tenantId={tenantId} tenantName={tenantName} events={complianceTimelineEvents} />
    <p className="text-xs text-muted-foreground">AWS-ready interface only. Security enforcement, authorization, audit authority, agreement evidence, review history, restrictions, protected documents, timeline evidence, and sensitive data remain backend responsibilities. No frontend control grants financial authority.</p>
  </div>;
}
